### ISSUE TITLE
botão HD troll

### ISSUE THREAD

**Issue by joenyrcouto** [LaksCastro/anime-dart#9]
tem alguns animes na plataforma que não tem HD, mas o botão de HD aparece mesmo assim. você aperta no botão e fica carregando infinitamente um EP que não tem. minha sugestão é tentar ocultar o botão nesses animes sem HD. 'U'

**Comment by ZaryImortal** [comment]
Já me ocorreu pensei que era minha net

**Comment by LaksCastro** [comment]
Sim, é um problema que já foi corrigido, mas ainda não foi publicado. Como não é um problema crítico, resolvi não me apressar e focar mais no desenvolvimento da [versão 2.0](https://github.com/LaksCastro/anime-dart/tree/2.0.0) que será totalmente diferente (para melhor) hehe =D

Até o domingo corrijo esse pequeno erro do botão, obrigado.

**Comment by joenyrcouto** [comment]
huahsuashu, entendi.
